from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

ASSETS_DIR = PROJECT_ROOT / "assets"
LETTERS_DIR = ASSETS_DIR / "New_Letters"
METADATA_DIR = ASSETS_DIR / "New_Letters_metadata"
RIVER_TILE_DIR = ASSETS_DIR / "g_river_tile_2"
RIBBON_PATH = RIVER_TILE_DIR / "final_river_ribbon_2.jpg"
TILE_MANIFEST = RIVER_TILE_DIR / "tile_manifest.txt"

OUTPUT_DIR = PROJECT_ROOT / "output"

METADATA_VERSION = 2
TARGET_RIVER_WIDTH = 14.0
MAX_TILT_DEG = 5.0
JUNCTION_OVERLAP_FACTOR = 0.72
BRIDGE_GAP_THRESHOLD = 8.0
RIVER_CROP_PAD_FACTOR = 1.05
LETTER_SAFE_PAD = 8
OPTIMIZER_BEAM_WIDTH = 14
ANGLE_MISMATCH_THRESHOLD = 35.0
OVERLAP_BLEND_WIDTH = 110
CANDIDATES_PER_LETTER = 10
MAX_OPTIMIZER_COMBINATIONS = 4096
DEFAULT_OUTPUT_SCALE = 1.0
JPEG_QUALITY = 95
LAYOUT_RANDOM_SEED = None
